# Makefile
# note: single space after $(.RECIPEPREFIX)
.RECIPEPREFIX := $(.RECIPEPREFIX) 

all:
  +node readWithTimeout.js
  +node readWithTimeout.js
  +node readWithTimeout.js
  +node readWithTimeout.js
